services:
  # Backend API Service
  - type: web
    name: jewgo-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DB_SSL
        value: true
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_TTL
        value: 15m
      - key: JWT_REFRESH_TTL
        value: 7d
      - key: JWT_ISSUER
        value: jewgo-auth
      - key: JWT_AUDIENCE
        value: jewgo-api
      # DATABASE_URL should be added manually in Render dashboard from your Neon connection string
      # Format: postgresql://user:password@host:port/database?sslmode=require
    healthCheckPath: /health
