# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'JewgoAppFinal' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Add react-native-vector-icons fonts to Xcode project
    require 'xcodeproj'
    
    fonts_dir = File.join(installer.sandbox.root, '../JewgoAppFinal')
    fonts = ['Feather.ttf', 'Ionicons.ttf', 'MaterialCommunityIcons.ttf', 'MaterialIcons.ttf']
    project_path = File.join(installer.sandbox.root, '../JewgoAppFinal.xcodeproj')
    project = Xcodeproj::Project.open(project_path)
    
    # Copy fonts to project directory
    fonts.each do |font|
      source = File.join(installer.sandbox.root, "../../node_modules/react-native-vector-icons/Fonts/#{font}")
      dest = File.join(fonts_dir, font)
      FileUtils.cp(source, dest) unless File.exist?(dest)
    end
    
    # Add fonts to Xcode project resources
    target = project.targets.first
    fonts_group = project.main_group.find_subpath('JewgoAppFinal', true)
    
    fonts.each do |font|
      font_path = File.join(fonts_dir, font)
      unless target.resources_build_phase.files.any? { |f| f.file_ref && f.file_ref.path == font }
        file_ref = fonts_group.new_reference(font)
        target.resources_build_phase.add_file_reference(file_ref)
      end
    end
    
    project.save
  end
end
