-- Job Seekers Sample Data
-- This migration populates the job_seekers table with realistic sample data for testing

-- Insert sample job seekers
INSERT INTO job_seekers (
    full_name,
    title,
    summary,
    email,
    phone,
    linkedin_url,
    city,
    state,
    zip_code,
    country,
    is_remote_ok,
    willing_to_relocate,
    experience_years,
    experience_level,
    skills,
    qualifications,
    languages,
    desired_job_types,
    desired_industries,
    desired_salary_min,
    desired_salary_max,
    availability,
    kosher_environment_preferred,
    shabbat_observant,
    jewish_organization_preferred,
    is_active,
    is_featured,
    is_verified,
    profile_completion_percentage
) VALUES 
-- Software Developer
(
    'Sarah Cohen',
    'Software Developer',
    'Passionate full-stack developer with 3 years of experience building scalable web applications. Strong background in React, TypeScript, and Node.js. Committed to writing clean, maintainable code and staying current with latest technologies.',
    'sarah.cohen@email.com',
    '(555) 123-4567',
    'https://linkedin.com/in/sarahcohen',
    'Brooklyn',
    'NY',
    '11201',
    'USA',
    true,
    false,
    3,
    'mid',
    ARRAY['React', 'TypeScript', 'Node.js', 'Python', 'JavaScript', 'PostgreSQL', 'Git', 'AWS'],
    ARRAY['Bachelor of Computer Science', 'AWS Certified Developer'],
    ARRAY['English', 'Hebrew'],
    ARRAY['full-time', 'contract'],
    ARRAY['Technology', 'Fintech', 'Healthcare Tech'],
    75000,
    95000,
    'immediate',
    true,
    true,
    true,
    true,
    true,
    true,
    95
),

-- Marketing Manager
(
    'David Goldstein',
    'Marketing Manager',
    'Results-driven marketing professional with 5 years of experience in digital marketing, SEO, and campaign management. Proven track record of increasing brand awareness and driving customer engagement through data-driven strategies.',
    'david.goldstein@email.com',
    '(555) 234-5678',
    'https://linkedin.com/in/davidgoldstein',
    'Manhattan',
    'NY',
    '10001',
    'USA',
    true,
    true,
    5,
    'mid',
    ARRAY['Digital Marketing', 'SEO', 'Google Analytics', 'Social Media', 'Content Marketing', 'Email Marketing', 'Campaign Management'],
    ARRAY['MBA Marketing', 'Google Analytics Certified', 'HubSpot Certified'],
    ARRAY['English', 'Spanish'],
    ARRAY['full-time'],
    ARRAY['Technology', 'Healthcare', 'Finance', 'Non-profit'],
    70000,
    90000,
    '2-weeks',
    false,
    false,
    false,
    true,
    false,
    true,
    90
),

-- Elementary Teacher
(
    'Rachel Levine',
    'Elementary Teacher',
    'Dedicated educator with 7 years of experience in elementary education. Passionate about inspiring young minds and creating inclusive learning environments. Specialized in curriculum development and special education.',
    'rachel.levine@email.com',
    '(555) 345-6789',
    'https://linkedin.com/in/rachellevine',
    'Queens',
    'NY',
    '11375',
    'USA',
    false,
    false,
    7,
    'senior',
    ARRAY['Curriculum Development', 'Classroom Management', 'Special Education', 'Reading Instruction', 'Math Instruction', 'Technology Integration'],
    ARRAY['Master of Education', 'Teaching License', 'Special Education Certification'],
    ARRAY['English', 'Hebrew'],
    ARRAY['full-time', 'part-time'],
    ARRAY['Education', 'Non-profit'],
    55000,
    70000,
    'summer-2024',
    true,
    true,
    true,
    true,
    true,
    true,
    100
),

-- Graphic Designer
(
    'Michael Rosen',
    'Graphic Designer',
    'Creative designer with 4 years of experience in visual communication. Strong portfolio in branding, UI/UX design, and digital marketing materials. Passionate about creating compelling visual experiences that connect with audiences.',
    'michael.rosen@email.com',
    '(555) 456-7890',
    'https://linkedin.com/in/michaelrosen',
    'Bronx',
    'NY',
    '10451',
    'USA',
    true,
    false,
    4,
    'mid',
    ARRAY['Adobe Creative Suite', 'UI/UX Design', 'Branding', 'Illustration', 'Web Design', 'Print Design', 'Figma', 'Sketch'],
    ARRAY['Bachelor of Fine Arts', 'Adobe Certified Expert'],
    ARRAY['English', 'Hebrew', 'Russian'],
    ARRAY['full-time', 'part-time', 'freelance'],
    ARRAY['Technology', 'Marketing', 'Non-profit', 'Creative Services'],
    50000,
    75000,
    'flexible',
    false,
    false,
    false,
    true,
    false,
    true,
    85
),

-- Accountant
(
    'Jessica Silver',
    'Accountant',
    'Detail-oriented accountant with 6 years of experience in financial analysis, tax preparation, and compliance. CPA certified with strong analytical skills and experience working with small to medium-sized businesses.',
    'jessica.silver@email.com',
    '(555) 567-8901',
    'https://linkedin.com/in/jessicasilver',
    'Staten Island',
    'NY',
    '10301',
    'USA',
    false,
    true,
    6,
    'senior',
    ARRAY['QuickBooks', 'Tax Preparation', 'Financial Analysis', 'CPA', 'Excel', 'Financial Reporting', 'Auditing', 'Compliance'],
    ARRAY['CPA License', 'Bachelor of Accounting', 'QuickBooks ProAdvisor'],
    ARRAY['English', 'Hebrew'],
    ARRAY['full-time', 'part-time'],
    ARRAY['Finance', 'Healthcare', 'Real Estate', 'Non-profit'],
    65000,
    85000,
    'immediate',
    true,
    true,
    true,
    true,
    true,
    true,
    95
),

-- Registered Nurse
(
    'Esther Klein',
    'Registered Nurse',
    'Compassionate RN with 8 years of experience in patient care. Specialized in emergency medicine and critical care. Committed to providing high-quality healthcare while respecting diverse cultural and religious needs.',
    'esther.klein@email.com',
    '(555) 678-9012',
    'https://linkedin.com/in/estherklein',
    'Brooklyn',
    'NY',
    '11215',
    'USA',
    false,
    false,
    8,
    'senior',
    ARRAY['Patient Care', 'Emergency Medicine', 'Critical Care', 'Medication Administration', 'Patient Assessment', 'CPR Certified'],
    ARRAY['Registered Nurse License', 'Bachelor of Nursing', 'BLS Certification', 'ACLS Certification'],
    ARRAY['English', 'Hebrew', 'Yiddish'],
    ARRAY['full-time', 'part-time'],
    ARRAY['Healthcare', 'Hospital', 'Clinic'],
    70000,
    95000,
    '1-month',
    true,
    true,
    true,
    true,
    false,
    true,
    90
),

-- Sales Representative
(
    'Benjamin Katz',
    'Sales Representative',
    'Results-oriented sales professional with 4 years of experience in B2B sales. Proven track record of exceeding sales targets and building strong client relationships. Excellent communication skills and customer service focus.',
    'benjamin.katz@email.com',
    '(555) 789-0123',
    'https://linkedin.com/in/benjaminkatz',
    'Manhattan',
    'NY',
    '10016',
    'USA',
    true,
    true,
    4,
    'mid',
    ARRAY['B2B Sales', 'Customer Relationship Management', 'Salesforce', 'Negotiation', 'Lead Generation', 'Account Management'],
    ARRAY['Bachelor of Business Administration', 'Salesforce Certified'],
    ARRAY['English', 'Hebrew'],
    ARRAY['full-time'],
    ARRAY['Technology', 'Finance', 'Healthcare', 'Real Estate'],
    60000,
    80000,
    '2-weeks',
    false,
    false,
    false,
    true,
    false,
    true,
    80
),

-- Social Worker
(
    'Miriam Schwartz',
    'Social Worker',
    'Licensed social worker with 6 years of experience in community outreach and case management. Passionate about helping individuals and families access resources and support services. Strong advocate for social justice.',
    'miriam.schwartz@email.com',
    '(555) 890-1234',
    'https://linkedin.com/in/miriamschwartz',
    'Queens',
    'NY',
    '11426',
    'USA',
    false,
    false,
    6,
    'senior',
    ARRAY['Case Management', 'Community Outreach', 'Crisis Intervention', 'Family Services', 'Mental Health Support', 'Resource Coordination'],
    ARRAY['Master of Social Work', 'Licensed Social Worker', 'Crisis Intervention Certification'],
    ARRAY['English', 'Hebrew', 'Spanish'],
    ARRAY['full-time', 'part-time'],
    ARRAY['Non-profit', 'Healthcare', 'Social Services', 'Education'],
    50000,
    70000,
    'immediate',
    true,
    true,
    true,
    true,
    false,
    true,
    85
);

-- Insert some sample job seeker applications to demonstrate the relationship
INSERT INTO job_seeker_applications (
    job_seeker_id,
    job_id,
    cover_letter,
    status,
    applied_at
) VALUES 
-- Sarah Cohen applied to a software developer job
(
    (SELECT id FROM job_seekers WHERE email = 'sarah.cohen@email.com'),
    (SELECT id FROM jobs WHERE title LIKE '%Software%' LIMIT 1),
    'Dear Hiring Manager, I am excited to apply for the Software Developer position. With 3 years of experience in React and Node.js, I am confident I can contribute to your development team.',
    'submitted',
    CURRENT_TIMESTAMP - INTERVAL '2 days'
),

-- David Goldstein applied to a marketing job
(
    (SELECT id FROM job_seekers WHERE email = 'david.goldstein@email.com'),
    (SELECT id FROM jobs WHERE title LIKE '%Marketing%' LIMIT 1),
    'I am writing to express my interest in the Marketing Manager position. My 5 years of digital marketing experience and proven results make me an ideal candidate.',
    'reviewing',
    CURRENT_TIMESTAMP - INTERVAL '5 days'
),

-- Rachel Levine applied to a teaching job
(
    (SELECT id FROM job_seekers WHERE email = 'rachel.levine@email.com'),
    (SELECT id FROM jobs WHERE title LIKE '%Teacher%' LIMIT 1),
    'As an experienced elementary teacher with 7 years of classroom experience, I am excited about the opportunity to join your educational team.',
    'interview',
    CURRENT_TIMESTAMP - INTERVAL '1 week'
);

COMMIT;
